Repository Las-Wonho/FirstWebDevelop, pull requests merged in 2018-08, with the labels that each got.

#1 Project setup
  .gitignore
  Contribute/Coding convention.md
  README.md
  Server/server.py
  Server/test/unit_test.py
Labels: new feature

#5 Add: Sample Img
  Client/Resources/Sample_Image.png
  Contribute/pip list.txt
Labels: new feature

#10 CI 셋팅 끝
  .circleci/config.yml
  Server/test/unit_test.py
Labels: enhancement, new feature

#11 Add New Endpoint
  Contribute/pip list.txt
  Server/server.py
  Server/test/unit_test.py
Labels: enhancement, new feature

#13 Required module to create template of HTML source
  Server/Client/Resources/Sample_Image.png
  Server/server.py
  Server/static/style.css
  Server/static/system.js
  Server/templates/404.html
  Server/templates/500.html
  Server/templates/basic.html
  Server/templates/gallery.html
  Server/templates/home.html
  Server/templates/info.html
  Server/templates/sign_in.html
  Server/templates/stat.html
  Server/test/unit_test.py
  requirements.txt
Labels: enhancement
